export const smallMap = [
  //**first row
  { type: "doubleCorner", rotation: "left", position: { x: 320, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 344, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 368, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 392, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 416, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 440, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 464, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 488, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 512, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 536, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 560, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 584, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 608, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 632, y: 110 } },
  { type: "cornerWall", rotation: "up", position: { x: 656, y: 110 } },
  {
    type: "cornerWall",
    rotation: "down",
    position: { x: 680, y: 110 },
    isFlip: true,
  },
  { type: "doubleWall", rotation: "up", position: { x: 704, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 728, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 752, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 776, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 800, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 824, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 848, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 872, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 896, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 920, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 944, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 968, y: 110 } },
  { type: "doubleWall", rotation: "up", position: { x: 992, y: 110 } },
  { type: "doubleCorner", rotation: "up", position: { x: 1016, y: 110 } },
  //**second row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 134 } },
  { type: "simpleWall", rotation: "right", position: { x: 656, y: 134 } },
  { type: "simpleWall", rotation: "left", position: { x: 680, y: 134 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 134 } },
  //**third row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 158 } },
  { type: "simpleCorner", rotation: "left", position: { x: 368, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 392, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 416, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 440, y: 158 } },
  { type: "simpleCorner", rotation: "up", position: { x: 464, y: 158 } },
  { type: "simpleCorner", rotation: "left", position: { x: 512, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 536, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 560, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 584, y: 158 } },
  { type: "simpleCorner", rotation: "up", position: { x: 608, y: 158 } },
  { type: "simpleWall", rotation: "right", position: { x: 656, y: 158 } },
  { type: "simpleWall", rotation: "left", position: { x: 680, y: 158 } },
  { type: "simpleCorner", rotation: "left", position: { x: 728, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 752, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 776, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 800, y: 158 } },
  { type: "simpleCorner", rotation: "up", position: { x: 824, y: 158 } },
  { type: "simpleCorner", rotation: "left", position: { x: 872, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 896, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 920, y: 158 } },
  { type: "simpleWall", rotation: "up", position: { x: 944, y: 158 } },
  { type: "simpleCorner", rotation: "up", position: { x: 968, y: 158 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 158 } },
  //**fourth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 182 } },
  { type: "simpleWall", rotation: "left", position: { x: 368, y: 182 } },
  { type: "simpleWall", rotation: "right", position: { x: 464, y: 182 } },
  { type: "simpleWall", rotation: "left", position: { x: 512, y: 182 } },
  { type: "simpleWall", rotation: "right", position: { x: 608, y: 182 } },
  { type: "miniCorner", rotation: "down", position: { x: 656, y: 182 } },
  { type: "miniCorner", rotation: "right", position: { x: 680, y: 182 } },
  { type: "simpleWall", rotation: "left", position: { x: 728, y: 182 } },
  { type: "simpleWall", rotation: "right", position: { x: 824, y: 182 } },
  { type: "simpleWall", rotation: "left", position: { x: 872, y: 182 } },
  { type: "simpleWall", rotation: "right", position: { x: 968, y: 182 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 182 } },
  //**fifth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 206 } },
  { type: "simpleCorner", rotation: "down", position: { x: 368, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 392, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 416, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 440, y: 206 } },
  { type: "simpleCorner", rotation: "right", position: { x: 464, y: 206 } },
  { type: "simpleCorner", rotation: "down", position: { x: 512, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 536, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 560, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 584, y: 206 } },
  { type: "simpleCorner", rotation: "right", position: { x: 608, y: 206 } },

  { type: "simpleCorner", rotation: "down", position: { x: 728, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 752, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 776, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 800, y: 206 } },
  { type: "simpleCorner", rotation: "right", position: { x: 824, y: 206 } },
  { type: "simpleCorner", rotation: "down", position: { x: 872, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 896, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 920, y: 206 } },
  { type: "simpleWall", rotation: "down", position: { x: 944, y: 206 } },
  { type: "simpleCorner", rotation: "right", position: { x: 968, y: 206 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 206 } },
  //** sixth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 230 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 230 } },
  //** seventh row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 254} },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 254} },
  //** eigth row
  { type: "doubleCorner", rotation: "down", position: { x: 320, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 344, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 368, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 392, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 416, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 440, y: 278} },
  { type: "miniCorner", rotation: "up", position: { x: 464, y: 278} },
  { type: "miniCorner", rotation: "left", position: { x: 872, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 896, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 920, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 944, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 968, y: 278} },
  { type: "doubleWall", rotation: "down", position: { x: 992, y: 278} },
  { type: "doubleCorner", rotation: "right", position: { x: 1016, y: 278} },
  //** ninth row
  { type: "doubleWall", rotation: "left", position: { x: 464, y: 302} },
  { type: "doubleWall", rotation: "right", position: { x: 872, y: 302} },
  //** tenth row
  { type: "doubleWall", rotation: "up", position: { x: 320, y: 326} },
  { type: "doubleWall", rotation: "up", position: { x: 1016, y: 326} },

  //** twelfth row
  { type: "doubleWall", rotation: "up", position: { x: 320, y: 374 } },
  { type: "doubleWall", rotation: "up", position: { x: 1016, y: 374 } },
  //** thirteenth row
  { type: "doubleCorner", rotation: "left", position: { x: 320, y: 398 } },
  { type: "doubleCorner", rotation: "up", position: { x: 1016, y: 398 } },
  //** forteenth row
  { type: "doubleCorner", rotation: "left", position: { x: 320, y: 422 } },
  { type: "doubleCorner", rotation: "up", position: { x: 1016, y: 422 } },
  //** fifteenth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 446 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 446 } },
  //** sixteeth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 470} },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 470} },
   //**seventeenth row
   { type: "doubleWall", rotation: "left", position: { x: 320, y: 494 } },
   { type: "simpleCorner", rotation: "left", position: { x: 368, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 392, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 416, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 440, y: 494 } },
   { type: "simpleCorner", rotation: "up", position: { x: 464, y: 494 } },
   { type: "simpleCorner", rotation: "left", position: { x: 512, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 536, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 560, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 584, y: 494 } },
   { type: "simpleCorner", rotation: "up", position: { x: 608, y: 494 } },
   
   { type: "simpleCorner", rotation: "left", position: { x: 728, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 752, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 776, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 800, y: 494 } },
   { type: "simpleCorner", rotation: "up", position: { x: 824, y: 494 } },
   { type: "simpleCorner", rotation: "left", position: { x: 872, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 896, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 920, y: 494 } },
   { type: "simpleWall", rotation: "up", position: { x: 944, y: 494 } },
   { type: "simpleCorner", rotation: "up", position: { x: 968, y: 494 } },
   { type: "doubleWall", rotation: "right", position: { x: 1016, y: 494 } },
  //**eighteenth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 518 } },
  { type: "simpleWall", rotation: "left", position: { x: 368, y: 518 } },
  { type: "simpleWall", rotation: "right", position: { x: 464, y: 518 } },
  { type: "simpleWall", rotation: "left", position: { x: 512, y: 518 } },
  { type: "simpleWall", rotation: "right", position: { x: 608, y: 518 } },
  { type: "miniCorner", rotation: "left", position: { x: 656, y: 518 } },
  { type: "miniCorner", rotation: "up", position: { x: 680, y: 518 } },
  { type: "simpleWall", rotation: "left", position: { x: 728, y: 518 } },
  { type: "simpleWall", rotation: "right", position: { x: 824, y: 518 } },
  { type: "simpleWall", rotation: "left", position: { x: 872, y: 518 } },
  { type: "simpleWall", rotation: "right", position: { x: 968, y: 518 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 518 } },
  //**nineteenth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 542 } },
  { type: "simpleCorner", rotation: "down", position: { x: 368, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 392, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 416, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 440, y: 542 } },
  { type: "simpleCorner", rotation: "right", position: { x: 464, y: 542 } },
  { type: "simpleWall", rotation: "right", position: { x: 656, y: 542 } },
   { type: "simpleWall", rotation: "left", position: { x: 680, y: 542 } },
  { type: "simpleCorner", rotation: "down", position: { x: 512, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 536, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 560, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 584, y: 542 } },
  { type: "simpleCorner", rotation: "right", position: { x: 608, y: 542 } },

  { type: "simpleCorner", rotation: "down", position: { x: 728, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 752, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 776, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 800, y: 542 } },
  { type: "simpleCorner", rotation: "right", position: { x: 824, y: 542 } },
  { type: "simpleCorner", rotation: "down", position: { x: 872, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 896, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 920, y: 542 } },
  { type: "simpleWall", rotation: "down", position: { x: 944, y: 542 } },
  { type: "simpleCorner", rotation: "right", position: { x: 968, y: 542 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 542 } },
  //**twentieth row
  { type: "doubleWall", rotation: "left", position: { x: 320, y: 566 } },
  { type: "simpleWall", rotation: "right", position: { x: 656, y: 566 } },
  { type: "simpleWall", rotation: "left", position: { x: 680, y: 566 } },
  { type: "doubleWall", rotation: "right", position: { x: 1016, y: 566 } },
  //**twenty first row
  { type: "doubleCorner", rotation: "down", position: { x: 320, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 344, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 368, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 392, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 416, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 440, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 464, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 488, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 512, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 536, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 560, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 584, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 608, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 632, y: 590 } },
  {
    type: "cornerWall",
    rotation: "up",
    position: { x: 656, y: 590 },
    isFlip: true,
  },
  { type: "cornerWall", rotation: "down", position: { x: 680, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 704, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 728, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 752, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 776, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 800, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 824, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 848, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 872, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 896, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 920, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 944, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 968, y: 590 } },
  { type: "doubleWall", rotation: "down", position: { x: 992, y: 590 } },
  { type: "doubleCorner", rotation: "right", position: { x: 1016, y: 590 } },
];
